#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII
bspc rule -a kitty state = floating rectangle=631x470+185+188

bspc config focused_border_color "#fabd2f"
bspc config normal_border_color "#3c3836"

bspc config border_width        5 
bspc config window_gap          35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec feh --bg-scale ~/Pictures/wall.jpg 	&
# exec picom --config ~/.config/picom.conf  	&
exec sh ~/.config/polybar/launch.sh         
#exec dunst -conf ~/.config/dunst/dunstrc

